// This file is automatically generated by SAPSec.DtoGenerator.
// Please do not manually edit this file or your changes will be lost when the file is regenerated.

using System.Diagnostics.CodeAnalysis;

namespace SAPSec.Data.Dto.Absence;

[ExcludeFromCodeCoverage]
public class EnglandAbsence
{
    public string Id { get; set; } = string.Empty;
    public decimal? Abs_Persistent_Boy_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Boy_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Boy_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Boy_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Boy_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Boy_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Secondary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Primary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Primary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Primary_Eng_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Secondary_Eng_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Secondary_Eng_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Secondary_Eng_Previous2_Pct { get; set; } = null;
}
