// This file is automatically generated by SAPSec.DtoGenerator.
// Please do not manually edit this file or your changes will be lost when the file is regenerated.

using System.Diagnostics.CodeAnalysis;

namespace SAPSec.Data.Dto.Absence;

[ExcludeFromCodeCoverage]
public class EstablishmentAbsence
{
    public string Id { get; set; } = string.Empty;
    public string LAId { get; set; } = string.Empty;
    public string LAName { get; set; } = string.Empty;
    public string RegionId { get; set; } = string.Empty;
    public string RegionName { get; set; } = string.Empty;
    public decimal? Abs_Persistent_Boy_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Boy_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Boy_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Dis_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EAL_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_EFL_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_Grl_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Persistent_NDi_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Boy_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Dis_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_EAL_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_EFL_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_Grl_Est_Previous2_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Est_Current_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Est_Previous_Pct { get; set; } = null;
    public decimal? Abs_Tot_NDi_Est_Previous2_Pct { get; set; } = null;
}
