using Newtonsoft.Json;
using SAPSec.Data.Common;
using SAPSec.Data.Common.Catalogue;
using SAPSec.Data.Common.Catalogue.Definitions;
using System.Text;

namespace SAPSec.DtoGenerator;

public class Program
{
    private const string GeneratedSubFolder = "Generated";
    private const string PrimarySubFolder = "PrimarySchools";

    private static readonly Dictionary<string, string> SubFolderMap = new()
    {
        [$"{GeneratedSubFolder}\\EstablishmentAbsence"] = "Absence",
        [$"{GeneratedSubFolder}\\LAAbsence"] = "Absence",
        [$"{GeneratedSubFolder}\\EnglandAbsence"] = "Absence",

        [$"{GeneratedSubFolder}\\EstablishmentDestinations"] = "KS4\\Destinations",
        [$"{GeneratedSubFolder}\\LADestinations"] = "KS4\\Destinations",
        [$"{GeneratedSubFolder}\\EnglandDestinations"] = "KS4\\Destinations",

        [$"{GeneratedSubFolder}\\EstablishmentPerformance"] = "KS4\\Performance",
        [$"{GeneratedSubFolder}\\EstablishmentSubjectEntries"] = "KS4\\Performance",
        [$"{GeneratedSubFolder}\\LAPerformance"] = "KS4\\Performance",
        [$"{GeneratedSubFolder}\\LASubjectEntries"] = "KS4\\Performance",
        [$"{GeneratedSubFolder}\\EnglandPerformance"] = "KS4\\Performance",

        [$"{GeneratedSubFolder}\\SimilarSchoolsPrimaryGroupsEntry"] = "SimilarSchools\\Primary",
        [$"{GeneratedSubFolder}\\SimilarSchoolsPrimaryValuesEntry"] = "SimilarSchools\\Primary",
        [$"{GeneratedSubFolder}\\SimilarSchoolsSecondaryGroupsEntry"] = "SimilarSchools\\Secondary",
        [$"{GeneratedSubFolder}\\SimilarSchoolsSecondaryValuesEntry"] = "SimilarSchools\\Secondary",

        [$"{PrimarySubFolder}\\EstablishmentPerformance"] = "KS2\\Performance",
        [$"{PrimarySubFolder}\\EstablishmentSubjectEntries"] = "KS2\\Performance",
        [$"{PrimarySubFolder}\\LAPerformance"] = "KS2\\Performance",
        [$"{PrimarySubFolder}\\LASubjectEntries"] = "KS2\\Performance",
        [$"{PrimarySubFolder}\\EnglandPerformance"] = "KS2\\Performance",
    };

    // Measures the pipeline stores as numbers (clean_numeric). Typed from the catalogue rather than the JSON,
    // because a column's first value may be null.
    private static readonly HashSet<string> NumericMeasures = CatalogueDefinitions.Rows()
        .Where(r => r.DataType == DataType.Double.DataMapValue())
        .Select(r => r.PropertyName)
        .ToHashSet(StringComparer.Ordinal);

    public static async Task Main(string[] args)
    {
        string baseDir = Project.FindProjectDirectoryDownwards("SAPSec.DtoGenerator.csproj");
        string jsonFilesDir = "..\\..\\SAPSec.Infrastructure\\Data\\Files";
        string generatedJsonDir = Path.Combine(baseDir, jsonFilesDir, GeneratedSubFolder);
        string primaryJsonDir = Path.Combine(baseDir, jsonFilesDir, PrimarySubFolder);
        string csDir = Path.Combine(baseDir, "..\\SAPSec.Data\\Dto");

        foreach (var csFile in Directory.GetFiles(csDir))
        {
            File.Delete(csFile);
        }

        foreach (var jsonFile in Directory.GetFiles(generatedJsonDir).Concat(Directory.GetFiles(primaryJsonDir)))
        {
            var fileName = new FileInfo(jsonFile).Name;

            if (fileName == "placeholder.txt")
            {
                continue;
            }

            Console.WriteLine($"Deserializing {jsonFile} ...");

            try
            {
                var json = await File.ReadAllTextAsync(jsonFile);
                var list = JsonConvert.DeserializeObject<List<Dictionary<string, object?>>>(json);

                var first = list?.FirstOrDefault();

                if (first is null)
                {
                    Console.WriteLine($"File {fileName} was empty.");
                    continue;
                }

                StringBuilder cs = new StringBuilder();
                var className = Path.GetFileNameWithoutExtension(jsonFile);
                var subFolder = SubFolderMap.TryGetValue($"{new DirectoryInfo(Path.GetDirectoryName(jsonFile)!).Name}\\{className}", out var sf)
                    ? sf
                    : "";

                var ns = "SAPSec.Data.Dto" + (subFolder.Any() ? "." + subFolder.Replace("\\", ".") : "");

                cs.AppendLine("// This file is automatically generated by SAPSec.DtoGenerator.");
                cs.AppendLine("// Please do not manually edit this file or your changes will be lost when the file is regenerated.");
                cs.AppendLine();
                if (className.EndsWith("GroupsEntry") || className.EndsWith("ValuesEntry"))
                {
                    cs.AppendLine("using SAPSec.Data.Repositories;");
                }
                cs.AppendLine("using System.Diagnostics.CodeAnalysis;");
                cs.AppendLine();
                cs.AppendLine($"namespace {ns};");
                cs.AppendLine();
                cs.AppendLine("[ExcludeFromCodeCoverage]");
                cs.Append($"public class {className}");
                if (className.EndsWith("GroupsEntry"))
                {
                    cs.Append(" : ISimilarSchoolsGroupsEntry");
                }
                if (className.EndsWith("ValuesEntry"))
                {
                    cs.Append(" : ISimilarSchoolsValuesEntry");
                }
                cs.AppendLine();
                cs.AppendLine("{");

                foreach (var (key, value) in first)
                {
                    var (type, deflt) = NumericMeasures.Contains(key) ? ("decimal?", "null") : value switch
                    {
                        int or long => ("int?", "null"),
                        double or float or decimal => ("decimal?", "null"),
                        _ => ("string", "string.Empty")
                    };
                    cs.AppendLine($"    public {type} {key} {{ get; set; }} = {deflt};");
                }

                cs.AppendLine("}");

                var destDir = Path.Combine(csDir, subFolder);
                Console.WriteLine($"Creating directory {destDir} ...");
                Directory.CreateDirectory(destDir);

                var csFilePath = Path.Combine(destDir, $"{className}.cs");
                Console.WriteLine($"Writing {csFilePath} ...");
                File.WriteAllText(csFilePath, cs.ToString(), new UTF8Encoding(false));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
