-- ================================================================
-- 00_cleanup.sql
-- Auto-generated by SAPData/Program.cs
-- Drops only explicitly listed raw tables before regeneration.
-- Recreates helper functions used by generated views.
-- ================================================================

\echo 'Cleaning up listed raw tables and regenerating helper functions...'

DO $$
DECLARE
  v_schema text := current_schema();
  r record;
  tables_to_rebuild text[] := ARRAY[]::text[];
BEGIN
  EXECUTE format('SET search_path TO %I', v_schema);

  -- Drop only listed raw tables
  FOR r IN
    SELECT schemaname, tablename
    FROM pg_tables
    WHERE schemaname = v_schema
      AND tablename LIKE 't\_%' ESCAPE '\'
  LOOP
    EXECUTE format('DROP TABLE IF EXISTS %I.%I CASCADE', r.schemaname, r.tablename);
  END LOOP;
END $$;

-- =========================
-- Cleaning helpers
-- =========================

CREATE OR REPLACE FUNCTION clean_int(value TEXT)
RETURNS INT
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    IF value IS NULL OR trim(value) IN ('', 'NE', 'N', 'na', 'n/a', 'N/A', 'SUPP', '.', '-', '--', 'z') THEN
        RETURN NULL;
    END IF;

    RETURN value::INT;

EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION clean_numeric(value TEXT)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    result NUMERIC;
BEGIN
    IF value IS NULL OR trim(value) IN ('', 'NE', 'N', 'na', 'n/a', 'N/A', 'SUPP', '.', '-', '--', 'z') THEN
        RETURN NULL;
    END IF;

    -- Same rules as the website's parser (SAPSec.Core MeasureHelper.ParseNullableDecimal):
    -- a trailing '%' is ignored, and anything that isn't a finite number is NULL.
    result := regexp_replace(trim(value), '%$', '')::NUMERIC;

    IF result IN ('NaN'::NUMERIC, 'Infinity'::NUMERIC, '-Infinity'::NUMERIC) THEN
        RETURN NULL;
    END IF;

    RETURN result;

EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION clean_date(value TEXT)
RETURNS DATE
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    IF value IS NULL OR trim(value) IN ('', 'na', 'n/a', 'N/A', '.', '-', '--') THEN
        RETURN NULL;
    END IF;

    RETURN value::DATE;

EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$;

\echo 'Cleanup complete.'
