// This file is automatically generated by SAPSec.DtoGenerator.
// Please do not manually edit this file or your changes will be lost when the file is regenerated.

using System.Diagnostics.CodeAnalysis;

namespace SAPSec.Data.Dto;

[ExcludeFromCodeCoverage]
public class EstablishmentWorkforce
{
    public string Id { get; set; } = string.Empty;
    public string LAId { get; set; } = string.Empty;
    public string LAName { get; set; } = string.Empty;
    public string RegionId { get; set; } = string.Empty;
    public string RegionName { get; set; } = string.Empty;
    public decimal? Workforce_PupTeaRatio_Est_Current_Num { get; set; } = null;
    public decimal? Workforce_TotPupils_Est_Current_Num { get; set; } = null;
}
